version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: golang-trading
    ports:
      - "5434:5432"
    volumes:
      - postgres_data_golang-trading:/var/lib/postgresql/data

volumes:
  postgres_data_golang-trading: