name: Build & Deploy 

on:
  push:
    tags:
      - 'release-v*' # Memicu saat ada tag seperti 'release-v1.0.0'

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step ini membuat 2 tag: satu sesuai versi rilis (cth: release-v1.0.0) dan satu lagi 'latest'
      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/golang-trading
          tags: |
            type=raw,value=${{ github.ref_name }}
            type=raw,value=latest

      # Push image dengan kedua tag (versi spesifik dan latest)
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest
    needs: build-and-push # Bergantung pada job build-and-push selesai
    
    # Izin yang diperlukan untuk otentikasi aman ke GCP
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # Otentikasi aman menggunakan Workload Identity Federation
      - name: Authenticate to Google Cloud
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      
      # Setup gcloud CLI setelah otentikasi berhasil
      - name: Set up Google Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      # Deploy menggunakan tag versi spesifik dari rilis, bukan 'latest'
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE }} \
            --image=docker.io/${{ secrets.DOCKERHUB_USERNAME }}/golang-trading:${{ github.ref_name }} \
            --platform=managed \
            --region=${{ secrets.CLOUD_RUN_REGION }} \
            --allow-unauthenticated